#!/bin/bash

## 不使用 submodule
# pull() {
# 	cd $1
# 	echo 
# 	echo "[pull $1 ...]"
# 	sh pull
# 	cd ..
# }

# for file in *; do
# 	if [ -f $file/pull ]; then
# 		pull $file
# 	fi
# done


## 方式1：同时更新parent、submodule；缺点是：没有进度显示
# git submodule update --remote --merge

## 方式2：
git submodule foreach "sh pull; echo ||:"

echo "update parent:"
git fetch origin

if !(git diff master origin/master --quiet); then
	git merge origin/master
fi


# issue: 更新pull时，无法删除旧的并创建
# git co origin/master pull push
