#!/bin/bash


param=$1
# 不使用 submodule，调用手动的脚本
if [[ $# -gt 1 ]]; then
	
	push() {
		cd $1

		if [[ $param -eq '1' ]]; then
			echo "[force pushing $1 ...]"
			git push origin master:master

		elif [ "`git st -s`" ]; then
			echo "[pushing $1 ...]"
			sh push
			echo
		else
			echo "[pass $1]"
		fi
		cd ..
	}

	for file in *; do
		if [ -f $file/push ]; then
			push $file
		fi
	done
	exit 0
fi

# 每个子模块都执行 sh push
git submodule foreach 'sh push; echo ||:'

echo "update parent:"
git add -A .
git diff --cached --quiet || 
	(git ci -m "fix" && git push --recurse-submodules=on-demand)
